### ISSUE TITLE
Add local_settings and local_plugins to gitignore

### ISSUE THREAD

**Issue by cedricpim** [taigacute/ThinkVim#34]
What do you think of adding local_settings.vim and local_plugins.yaml to gitignore? This way, I can clone the repo, do any local modifications and not make the repo dirty (so it is easier to keep it up to date). 

Otherwise, the alternative is forking your repo, do any local modifications and try to keep up my fork synchronized with yours.

PS: this looks pretty cool :clap:

**Comment by taigacute** [comment]
@cedricpim  hi  i add the local folder into the gitignore. why i create the local folder. because it easy to use no matter the people who is a new vim begginer. notice !! this is not a project .i only provide a config which is simple ,fatest, reasonable，full functioning，and some very cool plugins settings  ，when you grasp this config you can edit the any config files. then became yours config .

**Comment by cedricpim** [comment]
Thank you for the fast response.

I understand your point, but the whole repository is so neatly arranged that I thought it would be cool to just override personal settings.

Keep up the good work :+1:
